# Example: MinIO with virtual-host style bucket access
services:
  dnsmasq:
    image: ghcr.io/starburst997/docker-compose-wildcard:latest
    environment:
      WILDCARD_DOMAIN: minio
    cap_add:
      - NET_ADMIN
    networks:
      default:
        ipv4_address: 172.21.0.253
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DOMAIN: minio
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  # Application that needs to access MinIO with virtual-host style
  app:
    image: your-app
    dns: 172.21.0.253
    environment:
      S3_ENDPOINT: http://minio:9000
      # Now bucket.minio will resolve to MinIO

volumes:
  minio_data:

networks:
  default:
    ipam:
      config:
        - subnet: 172.21.0.0/16
