# GitHub Pages Configuration
title: Docker Compose Wildcard DNS
description: Enable wildcard subdomain resolution for Docker Compose environments
baseurl: ""
url: "https://docker-compose-wildcard.jd.boiv.in"

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
